<a href="https://colab.research.google.com/github/MelloWill36/Python_Para_Analise_Dados/blob/main/trabalho_pratico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Resolução do Trabalho Pratico

In [1]:
import numpy as np
import pandas as pd

In [14]:
# == CODIGO 01 == #
Z = np.zeros((4,))
print('Z: ', Z)
print('\n')

# == CODIGO 02 == #
Z = np.zeros((4,))
Z[1] = 1.
print('Z: ', Z)
print('\n')

# == CODIGO 03 == #
Z = np.zeros((4,))
Z[1:] = 1.
print('Z: ', Z)
print('\n')

# == CODIGO 04 == #
Z = np.zeros((4,))
Z[:-1] = 1.
print('Z: ', Z)
print('\n')

# == CODIGO 05 == #
X = np.ones((2,2)) + 1
print('X: \n', X)
print('\n')

# == CODIGO 06 == #
X = np.array([[1,2], [3,4]])
Y = X[0,:]
Y[1] = 10
print('X: \n', X)
print('\n')

# == CODIGO 07 == #
X = np.array([[1,3], [11,10]])
print(np.mean(X[X > np.pi]))
print('\n')

# == CODIGO 08 == #
data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# == CODIGO 09 == #
df = pd.DataFrame(data = data, index = labels)

# == CODIGO 10 == #
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])

Z:  [0. 0. 0. 0.]


Z:  [0. 1. 0. 0.]


Z:  [0. 1. 1. 1.]


Z:  [1. 1. 1. 0.]


X: 
 [[2. 2.]
 [2. 2.]]


X: 
 [[ 1 10]
 [ 3  4]]


10.5




In [3]:
Z = np.ones((4,)) 
Z[3] = 0.
print(Z)
Z = np.zeros((4, )) 
Z[:-1] = 1.
print(Z)
Z = np.zeros((4, )) 
Z[:3] = 1.
print(Z)
Z = np.ones((4,)) 
Z[-1] = 0.
print(Z)

[1. 1. 1. 0.]
[1. 1. 1. 0.]
[1. 1. 1. 0.]
[1. 1. 1. 0.]


In [4]:
X = np.array([2.] * 4).reshape(2, 2)
print(X)

[[2. 2.]
 [2. 2.]]


In [5]:
df.shape

(10, 4)

In [6]:
df['animal'].value_counts()

cat      4
dog      4
snake    2
Name: animal, dtype: int64

In [7]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [8]:
#df['visits']
#df.iloc[:, -2]
#df.loc[:, 'visits']
df.iloc[:, 3]

a    yes
b    yes
c     no
d    yes
e     no
f     no
g     no
h    yes
i     no
j     no
Name: priority, dtype: object

In [9]:
df.sort_values(by='visits', ascending=False)

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no

In [15]:
#y_true = np.array([1., 2., 1.])
#y_pred = np.array([1.1, 1.98, 1.05])

y_true = np.array([1., 2., 1.])
y_pred = np.array([-1., -2., -1.])


print(np.sqrt(((y_true-y_pred)**2).mean()))
print(((y_true-y_pred)**2).mean())

2.8284271247461903
8.0
